---
docker_disable_default_iptables_rules: yes
network_interface: "enp5s0"
neutron_external_interface: "enp6s0"
neutron_plugin_agent: linuxbridge

enable_chrony: "false"
prechecks_enable_host_ntp_checks: false



horizon_keystone_multidomain: yes




workaround_ansible_issue_8743: yes
config_strategy: "COPY_ALWAYS"
kolla_base_distro: "centos"
openstack_release: "11.0.0"
kolla_internal_vip_address: "192.168.20.99"
kolla_internal_fqdn: "{{ kolla_internal_vip_address }}"
kolla_external_vip_address: "{{ kolla_internal_vip_address }}"
dns_interface: "{{ network_interface }}"
enable_openstack_core: "yes"
enable_cinder: "yes"
enable_cinder_backend_nfs: "yes"
enable_designate: "yes"
enable_horizon: "{{ enable_openstack_core | bool }}"
enable_horizon_designate: "{{ enable_designate | bool }}"
enable_neutron_provider_networks: "yes"
enable_openvswitch: "{{ enable_neutron | bool and neutron_plugin_agent != 'linuxbridge' }}"
neutron_dns_integration: "yes"
neutron_dns_domain: "ostack.cosmicnet."
designate_backend: "bind9"
designate_ns_record: "ns1.ostack.cosmicnet"
  
#nova_backend_ceph: "yes"
nova_compute_virt_type: "kvm"

enable_haproxy: "yes"
enable_keepalived: "{{ enable_haproxy | bool }}"

