sinks:
  - name: cpu_sink
    publishers:
      - gnocchi://?filter_project=service&archive_policy=fleio_policy
  - name: network_sink
    publishers:
      - gnocchi://?filter_project=service&archive_policy=fleio_policy
  - name: object_storage_sink
    publishers:
      - gnocchi://?filter_project=service&archive_policy=fleio_policy
  - name: ceph_sink
    publishers:
      - gnocchi://?filter_project=service&archive_policy=fleio_policy
sources:
  - interval: 60
    name: cpu_source
    meters:
      - cpu
      - vcpus
    sinks:
      - cpu_sink
  - interval: 60
    name: network_source
    meters:
      - network.incoming.bytes
      - network.incoming.packets
      - network.outgoing.bytes
      - network.outgoing.packets
    sinks:
      - network_sink
  - interval: 60
    name: object_storage_source
    sinks:
      - object_storage_sink
    meters:
      - storage.objects
      - storage.objects.size
      - storage.objects.containers
      - storage.containers.objects
      - storage.containers.objects.size
  - interval: 60
    name: ceph_source
    sinks:
      - ceph_sink
    meters:
      - radosgw.objects
      - radosgw.objects.size
      - radosgw.objects.containers
      - radosgw.api.requests

